databases:
  - name: hatchPM-back
    databaseName: myapp
    user: myapp

services:
  - type: web
    name: mysite
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -p $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myapp
          property: connectionString
      # - key: RAILS_MASTER_KEY
      #   sync: false




# version: 2
# env_vars:
#   DATABASE_URL: postgres://postgres:<%= ENV['DATABASE_PASSWORD'] %>@localhost:5432/myapp_production
# services:
# - type: web
#   command: bundle exec puma -p $PORT
#   ports:
#     - 80:3000
