name: phase-3-sinatra-react-project
git:
  branch: main
services:
  - name: web
    command: bundle exec puma -p $PORT
    ports:
      - 80:3000
    env:
      DATABASE_URL: postgres://postgres:<%= ENV['DATABASE_PASSWORD'] %>@localhost:5432/myapp_production
